import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import '../../globals.css';
import NavigationSettings from './_component/navigation_settings';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'ProLink - Тохиргоо',
  description: 'Generated by create next app',
};
const inter = Manrope({ subsets: ['latin'] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex flex-col">
      <div className="">
        <NavigationSettings />
      </div>
      <div className={`${inter.className} min-h-screen  bg-secondary`}>
        <Suspense>{children}</Suspense>
      </div>
    </div>
  );
}
