import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import { Navigation } from "./_components/navigation";
import Footer from "./_components/footer";
import { Suspense } from "react";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "ProLink - Тохиргоо",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`min-h-screen bg-secondary ${montserrat.variable}`}>
      <Suspense>{children}</Suspense>
    </div>
  );
}
